### ISSUE TITLE
Animations don't stop when we update them to false

### ISSUE THREAD

**Issue by clovisdasilvaneto** [NevinhaJS/nevinha-js#51]

**Comment by fernandosouza** [comment]
In order to document my research:

I think I found a strange behaviour issue in the method: `updatePropsFromDiff` in the render() file.
`$parent` argument seems do not receive the correct value if it was called by the update lifecycle.

I can take a look later on how this method is called.

**Comment by clovisdasilvaneto** [comment]
Sounds good @fernandosouza ! Looks like a bug in the `updateElement` method, it is where we call the `updatePropsFromDiff` method
